### ISSUE TITLE
I can't seem to get this working with discord.js client intents

### ISSUE THREAD

**Issue by ghostyjag** [danxfisher/Plex-Discord-Bot#20]
Everytime I try and launch the bot, I get the following error:

TypeError [ClientMissingIntents]: Valid intents must be provided for the Client.
    at Client._validateOptions (C:\Plex-Discord-Bot-master\node_modules\discord.js\src\client\Client.js:480:13)
    at new Client (C:\Plex-Discord-Bot-master\node_modules\discord.js\src\client\Client.js:78:10)
    at Object.<anonymous> (C:\Plex-Discord-Bot-master\index.js:8:16)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ClientMissingIntents'

**Comment by ghostyjag** [comment]
I realized I was using it with v14 requiring the client intents. I have been able to resolve this
