### ISSUE TITLE
having trouble starting

### ISSUE THREAD

**Issue by Myrkie** [danxfisher/Plex-Discord-Bot#3]
Having trouble starting after completing setup

module.js:538
    throw err;
    ^

Error: Cannot find module 'discord.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\Windows files\Desktop\Discord\index.js:2:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by Myrkie** [comment]
Edit
Tried going back since I missed install for NPM
after going to the the install location for the bot typed npm install and I get this error with no new files
λ npm install                                                                                     
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Administrator\package.json'  
npm notice created a lockfile as package-lock.json. You should commit this file.                  
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\package.json'     
npm WARN Administrator No description                                                             
npm WARN Administrator No repository field.                                                       
npm WARN Administrator No README data                                                             
npm WARN Administrator No license field.                                                          
                                                                                                  
up to date in 0.038s        
                                                                      
I went ahead and tried to install the discord.js file with npm install --save discord.js
now I get a complexity different error
λ node index.js
module.js:538
    throw err;
    ^

Error: Cannot find module 'plex-api'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\Windows files\Desktop\Discord\commands\plex.js:2:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by Myrkie** [comment]
issue was solved after tracking down plex-api and discord.js after npm install failed
