### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by ZantooTheGreat** [danxfisher/Plex-Discord-Bot#9]
Hi, I keep getting the following error after I authorize my bot:

c:\Users\Zantri-La\Desktop\PlexPy\Plex-Discord-Bot-master>node index.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'discord.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\Zantri-La\Desktop\PlexPy\Plex-Discord-Bot-master\index.js:2:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

Thoughts?

**Comment by danxfisher** [comment]
Did you type `npm install` to install all of the dependencies?
